Support K8s
bizflycloud/terraform-provider-bizflycloud pull request #12
Opened 2021-02-19 07:25 UTC by tung491

2021-02-19 08:42 UTC, greatbn commented
Can you add some examples for this resource ? @tung491

2021-02-19 10:03 UTC, BoTranVan commented on bizflycloud/provider.go
> +			"bizflycloud_kubernetes":                       resourceBizFlyKubernetes(),
nên sử dụng prefix là resourceBizFlyCloud hoặc datasourceBizFlyCloudcho đồng bộ

2021-02-19 10:04 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +				Required: true,
trường này người dùng không hề biết giá trị khi tạo nên cần phải để Compute thay vì Required

2021-02-19 10:04 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +				Required: true,
trường này người dùng không hề biết giá trị khi tạo nên cần phải để Compute thay vì Required

2021-02-19 10:10 UTC, tung491 commented on bizflycloud/provider.go
> +			"bizflycloud_kubernetes":                       resourceBizFlyKubernetes(),
Done rồi ạ

2021-02-19 10:13 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +		WorkerPools: d.Get("worker_pools").([]gobizfly.WorkerPool),
chỗ này khi đọc từ spec của tf ra thì không cast được như này mà cần phải có hàm xử lý riêng.

2021-02-19 10:18 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	if err != nil {
đoạn này ở dưới resourceBizFlyCloudClusterRead có rồi nên chỉ cần return function là đủ.

2021-02-19 10:18 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	cluster, err := client.KubernetesEngine.Create(context.Background(), ccrq)
tạo object thì cần phải chờ cho nó ready (tạo xong) do nếu sau này nếu có thêm datasource thì nó sẽ không đọc được thông tin.

2021-02-19 10:19 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	return resourceBizFlyCloudClusterRead(d, meta)
phần read này cũng vậy phải chờ create hoặc update xong mới có đủ thông tin để đọc và coi là hoàn thành.

2021-02-19 10:20 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	if d.HasChange("worker_pools") {
phần này cần phải kiểm tra điều kiện khi nào thì được gửi request update

2021-02-19 10:22 UTC, pmint93 commented
Để ý có một số trường chỉ xuất hiện sau khi cluster được tạo (VD: created_by) thì để dạng Computed như Bộ có comment

Các trường required/optional trong API docs có ghi rõ, chỉ định chính xác theo

Đồng thời tạm bỏ/hidden các trường sau:

- Cluster: auto_upgrade, enable_cloud

- Worker pool: version

2021-02-19 10:33 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +		newPools := d.Get("worker_pools").([]gobizfly.WorkerPool)
chỗ này cũng phải xử lý riêng chứ không cast được.

2021-02-19 10:38 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			if isOldPool[pool.Name] && !isNewPool[pool.Name] {
chỗ này pool.Name trong isOldPool chắc chắn có nhưng chưa chắc đã có ở isNewPool

2021-02-19 12:15 UTC, tung491 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			if isOldPool[pool.Name] && !isNewPool[pool.Name] {
![image](https://user-images.githubusercontent.com/29272893/108503295-b6cf1000-72e6-11eb-85f3-846cca1ce174.png) nếu ko thì nó nhả false ạ

2021-02-19 12:15 UTC, tung491 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			if isOldPool[pool.Name] && !isNewPool[pool.Name] {
![image](https://user-images.githubusercontent.com/29272893/108503352-cea69400-72e6-11eb-8056-cdf46d4c4b1d.png)

2021-02-19 13:23 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			if isOldPool[pool.Name] && !isNewPool[pool.Name] {
ừm.

2021-02-19 13:44 UTC, tung491 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	if d.HasChange("worker_pools") {
Anh nói rõ vụ này được không ạ. Em không hiểu ý lắm

2021-02-20 01:32 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +				Required: true,
thằng này nên là Optional

2021-02-20 01:32 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			},
Ẩn đi. => bỏ khỏi schema.

2021-02-20 01:32 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			Required: true,
bỏ khỏi schema

2021-02-20 01:32 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	if err != nil {
nếu không nhầm thì lỗi return và in trên màn hình sẽ là: Error creating cluster: Error creating cluster: xxxx

2021-02-20 01:32 UTC, BoTranVan commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +	if d.HasChange("worker_pools") {
@pmint93 phần này có cần phải kiểm tra không?

2021-02-23 03:13 UTC, pmint93 requested changes

2021-02-23 03:13 UTC, pmint93 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			Optional: true,
Required: true

2021-02-23 03:13 UTC, pmint93 commented on website/docs/r/kubernetes.html.markdown
> +  * `volume_type` - (Optional) The volume type
Required

2021-02-23 03:13 UTC, pmint93 commented on website/docs/r/kubernetes.html.markdown
> +  * `volume_size` - (Optional) The volume size
Required

2021-02-23 03:13 UTC, pmint93 commented on website/docs/r/kubernetes.html.markdown
> +  * `enable_autoscaling` - (Required) Enable auto scaling or not
Optional

2021-02-23 03:13 UTC, pmint93 commented on website/docs/r/kubernetes.html.markdown
> +  * `min_size` - (Required) The number of the minimum node
Optional

2021-02-23 03:13 UTC, pmint93 commented on website/docs/r/kubernetes.html.markdown
> +  * `max_size` - (Required) The number of the maximum node
Optional

2021-02-23 03:13 UTC, pmint93 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			Required: true,
Optional

2021-02-23 03:13 UTC, pmint93 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			Required: true,
Optional

2021-02-23 03:13 UTC, pmint93 commented on bizflycloud/resource_bizflycloud_kubernetes.go
> +			Required: true,
Optional

2021-02-23 07:55 UTC, pmint93 approved these changes

2021-02-23 08:27 UTC, merged