Bcu 22#support vpc network
bizflycloud/terraform-provider-bizflycloud pull request #21
Opened 2021-07-07 10:53 UTC by dactoankmapydev

- Create,  update, delete VPC
- Datasource VPC: Input: VPC network name lấy vpc_network_id

2021-07-07 13:29 UTC, greatbn commented on bizflycloud/resource_bizflycloud_vpc_network_test.go
> +package bizflycloud
Please add more test cases for this.

2021-07-08 03:10 UTC, dactoankmapydev commented on bizflycloud/resource_bizflycloud_vpc_network_test.go
> +package bizflycloud
I have added more test cases for this.

2021-07-10 01:38 UTC, greatbn requested changes

2021-07-10 01:38 UTC, greatbn commented on examples/vpc_network/outputs.tf
> +}
no new line

2021-07-10 01:38 UTC, greatbn commented on examples/vpc_network/terraform.tfvars
> +vpc_network_name = "vpc_toannd"
no new line

2021-07-10 01:38 UTC, greatbn commented on examples/vpc_network/variables.tf
> +}
no new line

2021-07-10 01:38 UTC, greatbn commented on examples/vpc_network/main.tf
>  }
no new line

2021-07-12 04:30 UTC, merged